language: csharp
dist: trusty
os: linux
mono: none
dotnet: 2.1
install:
  - dotnet restore
script:
  - dotnet build MimeSharp/MimeSharp.csproj
  - dotnet test MimeSharp.Tests/MimeSharp.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  - dotnet pack /p:Configuration=Release
